package exception_Handling_Concepts;

public class FullyCheckedPartiallyChecked {

	
	// IOEXCEPTION -> FULLY CHECKED [CHILD]
	//RUNTIME EXCEPTION -> PARTIALLY CHECKED 
	//INTRUPPTED EXCEPTION -> FULLY CHECKED 
	//ERROR -> UNCHECKED 
	//THROWABLE -> CHECKED , PARTIALLY CHECKED
	//AIRTHMETIC EXCEPTION -> PARTIALLY CHECKED [UNCHECKED]
	//NULL POINTER -> PARTIALLY CHECKED [UNCHECKED]
	//EXCEPTION -> PARTIALLY CHECKED
	//FILENOTFOUND EXCEPTION -> FULLY CHECKED 
}
